[package]
name = "rustc_search_graph"
version = "0.1.0"
edition = "2021"

[dependencies]
# tidy-alphabetical-start
derivative = "2.2.0"
itertools = "0.12"
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_index = { path = "../rustc_index" }
tracing = "0.1"
# tidy-alphabetical-end
